<a href="https://colab.research.google.com/github/tishbian/Data-Science/blob/main/Ds_Numpyfunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Creating Arrays

In [ ]:
import numpy as np

In [ ]:
ary = np.array([1,2,3,4,5])
print(ary)

[1 2 3 4 5]


##Creating an array of zeroes

In [ ]:
ar = np.zeros(5)
print (ar)

[0. 0. 0. 0. 0.]


##Creating an array using range function

In [ ]:
ay = np.arange(1, 9)
print (ay)

[1 2 3 4 5 6 7 8]


##Creating an array of ones

In [ ]:
an = np.ones(5)
print(an)

[1. 1. 1. 1. 1.]


##Creating an array with evenly spaced values

In [ ]:
Ap = np.linspace(3, 8)
print (Ap)

[3.         3.10204082 3.20408163 3.30612245 3.40816327 3.51020408
 3.6122449  3.71428571 3.81632653 3.91836735 4.02040816 4.12244898
 4.2244898  4.32653061 4.42857143 4.53061224 4.63265306 4.73469388
 4.83673469 4.93877551 5.04081633 5.14285714 5.24489796 5.34693878
 5.44897959 5.55102041 5.65306122 5.75510204 5.85714286 5.95918367
 6.06122449 6.16326531 6.26530612 6.36734694 6.46938776 6.57142857
 6.67346939 6.7755102  6.87755102 6.97959184 7.08163265 7.18367347
 7.28571429 7.3877551  7.48979592 7.59183673 7.69387755 7.79591837
 7.89795918 8.        ]


##Creating an Identity Matrix

In [ ]:
matrix = np.eye (3,3)
print (matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##Array Information

###Returns the Shape of the matrix

In [ ]:
matrix = np.eye(3,3)
print (matrix)
Shape_matrix = matrix.shape
print(Shape_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


###Returns the No of Dimensions

In [ ]:
matrix = np.eye(3,3)
print (matrix)
No_dimension = matrix.ndim
print(No_dimension)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2


###Returns the No of Elements in the Array

In [ ]:
matrix = np.eye(3,3)
print (matrix)
No_elements = matrix.size
print(No_elements)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
9


###Returns the datatype of the elements

In [ ]:
matrix = np.eye(3,3)
print (matrix)
Data_type = matrix.dtype
print(Data_type)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64


##Array Operations

###Elements wise Addition

In [ ]:
a = np.arange(1, 6)
print(a)
b = np.arange(2, 7)
print(b)
c = np.add(a, b)
print(c)

[1 2 3 4 5]
[2 3 4 5 6]
[ 3  5  7  9 11]


###Element wise Subtraction

In [ ]:

a = np.arange(1, 6)
print(a)
b = np.arange(2, 7)
print(b)
c = np.subtract(a, b)
print(c)

[1 2 3 4 5]
[2 3 4 5 6]
[-1 -1 -1 -1 -1]


###Element wise Multiplication

In [ ]:

a = np.arange(1, 6)
print(a)
b = np.arange(2, 7)
print(b)
c = np.multiply(a, b)
print(c)

[1 2 3 4 5]
[2 3 4 5 6]
[ 2  6 12 20 30]


###Element wise Division

In [ ]:

a = np.arange(1, 6)
print(a)
b = np.arange(1, 6)
print(b)
c = np.divide(a, b)
print(c)

[1 2 3 4 5]
[1 2 3 4 5]
[1. 1. 1. 1. 1.]


###Dot Products of two Arrays

In [ ]:

a = np.arange(1, 6)
print(a)
b = np.arange(2, 7)
print(b)
c = np.dot(a, b)
print(c)

[1 2 3 4 5]
[2 3 4 5 6]
70


##Array Manipulation

###Reshape an Array

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###Concatenate of two arrays

In [ ]:

a = np.arange(1, 6)
print(a)
b = np.arange(2, 7)
print(b)
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5]
[2 3 4 5 6]
[1 2 3 4 5 2 3 4 5 6]


###Split an array into two sub arrays

In [ ]:

a = np.arange(1, 6)
print(a)
b = np.arange(2, 7)
print(b)
c = np.concatenate((a, b))
print(c)
split_array = np.split(c, 2)
print(split_array)

[1 2 3 4 5]
[2 3 4 5 6]
[1 2 3 4 5 2 3 4 5 6]
[array([1, 2, 3, 4, 5]), array([2, 3, 4, 5, 6])]


###Transpose an Array

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)
tran_matrix = np.transpose(matrix)
print(tran_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


##Trignometric Functions

In [ ]:
import math

###Sine Function

In [ ]:
sin_value = math.sin(math.radians(30))
print("Sine:", sin_value)

Sine: 0.49999999999999994


###Cosine Function

In [ ]:
cos_value = math.cos(math.radians(60))  # math.cos takes radians, so convert degrees to radians
print("Cosine:", cos_value)

Cosine: 0.5000000000000001


##Tanget Function

In [ ]:
tan_value = math.tan(math.radians(45))  # math.tan takes radians, so convert degrees to radians
print("Tangent:", tan_value)

Tangent: 0.9999999999999999


##Arcsine Function

In [ ]:
asin_value = math.degrees(math.asin(0.5))  # math.asin returns radians, so convert radians to degrees
print("Arcsine:", asin_value)

Arcsine: 30.000000000000004


##Arccosine Function

In [ ]:
acos_value = math.degrees(math.acos(0.5))  # math.acos returns radians, so convert radians to degrees
print("Arccosine:", acos_value)

Arccosine: 60.00000000000001


##Arctanget Function

In [ ]:
atan_value = math.degrees(math.atan(1))  # math.atan returns radians, so convert radians to degrees
print("Arctangent:", atan_value)

Arctangent: 45.0


###Inverse Trignometric function

In [ ]:

# Example values
x = 0.5

# arcsine (inverse sine)
arcsine_result = math.asin(x)
print(f'arcsin({x}) = {math.degrees(arcsine_result)} degrees')  # Convert radians to degrees for better readability

# arccosine (inverse cosine)
arccosine_result = math.acos(x)
print(f'arccos({x}) = {math.degrees(arccosine_result)} degrees')

# arctangent (inverse tangent)
arctangent_result = math.atan(x)
print(f'arctan({x}) = {math.degrees(arctangent_result)} degrees')

arcsin(0.5) = 30.000000000000004 degrees
arccos(0.5) = 60.00000000000001 degrees
arctan(0.5) = 26.56505117707799 degrees


###Mathematical Functions

###Sum of Arry Elements

In [ ]:
# Example array
my_array = [1, 2, 3, 4, 5]
array_sum = sum(my_array)
print(f"Sum of array elements: {array_sum}")

Sum of array elements: 15


###Mean of Array Elements

In [ ]:
import numpy as np
my_array = [1, 2, 3, 4, 5]
array_mean = np.mean(my_array)
print(f"Mean of array elements: {array_mean}")

Mean of array elements: 3.0


###Median of Array Elements

In [ ]:

my_array = [1, 2, 3, 4, 5]
array_median = np.median(my_array)
print(f"Median of array elements: {array_median}")

Median of array elements: 3.0


###Standard Deviation

In [ ]:

my_array = [1, 2, 3, 4, 5]
array_std = np.std(my_array)
print(f"Standard deviation of array elements: {array_std}")

Standard deviation of array elements: 1.4142135623730951


###Minimum and Maximum Values

In [ ]:

my_array = [1, 2, 3, 4, 5]
array_min = min(my_array)
array_max = max(my_array)
print(f"Minimum value: {array_min}")
print(f"Maximum value: {array_max}")

Minimum value: 1
Maximum value: 5


##Statical Function

###Random integer

In [ ]:

import random
random_integer = random.randint(1, 10)  # Generates a random integer between 1 and 10 (inclusive)
print (random_integer)

5


###Random Shuffle

In [ ]:
import random
my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)  # Shuffles the list in-place
print (my_list)

[4, 1, 5, 3, 2]


###Random values in a given shape

In [ ]:

import numpy as np

# Set a seed for reproducibility (optional)
np.random.seed(42)

# Specify the shape of the array
shape = (3, 4)  # Example: 3 rows, 4 columns

# Generate random values in the specified shape
random_array = np.random.rand(*shape)  # For values between 0 and 1
# Or you can use np.random.randint for integer values: random_array = np.random.randint(1, 10, size=shape)

# Print the result
print("Random Array:")
print(random_array)

Random Array:
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]


###Random Values in a normal distribution

In [ ]:

import random
mean = 0
std_dev = 1
random_gaussian = random.gauss(mean, std_dev)  # Generates a random number from a Gaussian distribution
print(random_gaussian)

0.9442272210501224


###Logical Operators:

AND: and
OR: or
NOT: not

In [ ]:
a = True
b = False
print(a and b)  # False
print(a or b)   # True
print(not a)    # False

False
True
False


##Linear Algebra

##Matrix inversion

In [ ]:

import numpy as np

# Create a vector
vector = np.array([1, 2, 3])

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(vector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [ ]:
import numpy as np

def inverse_matrix(matrix):
    try:
        # Use numpy's linear algebra module to calculate the inverse
        inv_matrix = np.linalg.inv(matrix)
        return inv_matrix
    except np.linalg.LinAlgError:
        # Handle the case where the matrix is singular or not square
        print("Matrix inversion is not possible for the given matrix.")

# Example usage:
matrix_to_invert = np.array([[1, 2], [3, 4]])
result = inverse_matrix(matrix_to_invert)

if result is not None:
    print("Original Matrix:")
    print(matrix_to_invert)
    print("\nInverse Matrix:")
    print(result)


Original Matrix:
[[1 2]
 [3 4]]

Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


###Determinant of Matrix

In [ ]:
import numpy as np

# Example matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Calculate the determinant
determinant_value = np.linalg.det(matrix)

# Display the determinant
print("Matrix:")
print(matrix)
print("Determinant:", determinant_value)


Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004


##Eigen Values and Eigen Vector

In [ ]:
import numpy as np

# Example matrix
matrix = np.array([[4, -2],
                   [1,  1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Display the results
print("Matrix:")
print(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Matrix:
[[ 4 -2]
 [ 1  1]]
Eigenvalues: [3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


##Sorting

###Sort an Array

In [ ]:
# Example array
my_array = [4, 2, 8, 1, 7]

# Using sort() method to sort the array in-place
my_array.sort()

# Display the sorted array
print("Sorted Array:", my_array)


Sorted Array: [1, 2, 4, 7, 8]


###Save an Array to a Binary File

In [ ]:
import numpy as np

# Example array
my_array = np.array([1, 2, 3, 4, 5])

# Save the array to a binary file
np.save("my_array.npy", my_array)
# Load the array from the binary file
loaded_array = np.load("my_array.npy")

# Display the loaded array
print("Loaded Array:", loaded_array)
# Save multiple arrays to a single binary file
np.savez("my_arrays.npz", array1=my_array, array2=loaded_array)

# Load the arrays back from the binary file
loaded_data = np.load("my_arrays.npz")

# Access individual arrays using keys
array1 = loaded_data['array1']
array2 = loaded_data['array2']

# Display the loaded arrays
print("Loaded Array 1:", array1)
print("Loaded Array 2:", array2)


Loaded Array: [1 2 3 4 5]
Loaded Array 1: [1 2 3 4 5]
Loaded Array 2: [1 2 3 4 5]


###Load an Array from a Binary File

In [ ]:
import numpy as np

# Load the array from the binary file
loaded_array = np.load("my_array.npy")

# Display the loaded array
print("Loaded Array:", loaded_array)
# Load multiple arrays from a single binary file
loaded_data = np.load("my_arrays.npz")

# Access individual arrays using keys
array1 = loaded_data['array1']
array2 = loaded_data['array2']

# Display the loaded arrays
print("Loaded Array 1:", array1)
print("Loaded Array 2:", array2)


Loaded Array: [1 2 3 4 5]
Loaded Array 1: [1 2 3 4 5]
Loaded Array 2: [1 2 3 4 5]
